"""baseline persistent instagram identity

Revision ID: cbc429210ca8
Revises: 
Create Date: 2026-09-08 14:01:34.009954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbc429210ca8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('biography', sa.Text(), nullable=False),
    sa.Column('profile_picture_url', sa.Text(), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=True),
    sa.Column('following_count', sa.Integer(), nullable=True),
    sa.Column('instagram_media_count', sa.Integer(), nullable=True),
    sa.Column('crawled_media_count', sa.Integer(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crawl_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crawl_sessions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_crawl_sessions_username'), ['username'], unique=True)

    op.create_table('crawled_media',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('media_id', sa.String(length=255), nullable=False),
    sa.Column('shortcode', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.String(length=32), nullable=False),
    sa.Column('permalink', sa.Text(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['crawl_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'media_id', name='uq_instagram_media_source_media_id')
    )
    with op.batch_alter_table('crawled_media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crawled_media_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crawled_media_shortcode'), ['shortcode'], unique=False)

    op.create_table('import_drafts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('crawl_session_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crawl_session_id'], ['crawl_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crawl_session_id', name='uq_import_workspace_source')
    )
    with op.batch_alter_table('import_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_drafts_crawl_session_id'), ['crawl_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_drafts_status'), ['status'], unique=False)

    op.create_table('crawled_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('media_id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['crawled_media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_id', 'asset_type', 'position', name='uq_instagram_asset_media_type_position')
    )
    with op.batch_alter_table('crawled_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crawled_assets_media_id'), ['media_id'], unique=False)

    op.create_table('import_draft_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('draft_id', sa.String(length=36), nullable=False),
    sa.Column('crawled_media_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crawled_media_id'], ['crawled_media.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['draft_id'], ['import_drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draft_id', 'crawled_media_id', name='uq_import_workspace_item_media')
    )
    with op.batch_alter_table('import_draft_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_draft_items_crawled_media_id'), ['crawled_media_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_draft_items_draft_id'), ['draft_id'], unique=False)

    op.create_table('import_draft_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('draft_item_id', sa.String(length=36), nullable=False),
    sa.Column('crawled_asset_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['crawled_asset_id'], ['crawled_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['draft_item_id'], ['import_draft_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draft_item_id', 'crawled_asset_id', name='uq_import_asset_selection_item_asset')
    )
    with op.batch_alter_table('import_draft_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_draft_assets_crawled_asset_id'), ['crawled_asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_draft_assets_draft_item_id'), ['draft_item_id'], unique=False)

    op.create_table('import_draft_product_data',
    sa.Column('draft_item_id', sa.String(length=36), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('sale_price', sa.Integer(), nullable=True),
    sa.Column('list_price', sa.Integer(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('colors', sa.JSON(), nullable=False),
    sa.Column('sizes', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['draft_item_id'], ['import_draft_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('draft_item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('import_draft_product_data')
    with op.batch_alter_table('import_draft_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_draft_assets_draft_item_id'))
        batch_op.drop_index(batch_op.f('ix_import_draft_assets_crawled_asset_id'))

    op.drop_table('import_draft_assets')
    with op.batch_alter_table('import_draft_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_draft_items_draft_id'))
        batch_op.drop_index(batch_op.f('ix_import_draft_items_crawled_media_id'))

    op.drop_table('import_draft_items')
    with op.batch_alter_table('crawled_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crawled_assets_media_id'))

    op.drop_table('crawled_assets')
    with op.batch_alter_table('import_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_drafts_status'))
        batch_op.drop_index(batch_op.f('ix_import_drafts_crawl_session_id'))

    op.drop_table('import_drafts')
    with op.batch_alter_table('crawled_media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crawled_media_shortcode'))
        batch_op.drop_index(batch_op.f('ix_crawled_media_session_id'))

    op.drop_table('crawled_media')
    with op.batch_alter_table('crawl_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crawl_sessions_username'))
        batch_op.drop_index(batch_op.f('ix_crawl_sessions_status'))

    op.drop_table('crawl_sessions')
    # ### end Alembic commands ###
